<script lang="ts">
  import type { Post, ReactionType } from '../../../src/lib/social-store';
  import {
    addComment,
    bookmarkPost,
    likePost,
    loadFeed,
    reactToPost,
    repostPost,
    setHashtagFilter,
    toggleCommentLike,
    votePoll
  } from '../../../src/lib/social-store';
  import CommentComposer from '../comments/CommentComposer.svelte';
  import CommentList from '../comments/CommentList.svelte';
  import PostBody from './PostBody.svelte';
  import PostHeader from './PostHeader.svelte';
  import PostMedia from './PostMedia.svelte';
  // @ts-ignore - Svelte component default export is generated by the Svelte compiler.
  import ReactionBar from '../reactions/ReactionBar.svelte';

  export let post: Post;

  function handleReaction(reaction: ReactionType) {
    reactToPost(post.id, reaction);
  }

  function handleHashtagSelect(event: CustomEvent<{ tag: string }>) {
    setHashtagFilter(event.detail.tag);
    void loadFeed();
  }
</script>

<article class="rounded-3xl border border-slate-200 bg-white p-5 dark:border-white/10 dark:bg-slate-900">
  <div class="flex gap-3">
    <img src={post.author.avatar} alt={post.author.displayName} class="h-11 w-11 flex-shrink-0 rounded-full object-cover" />
    <div class="min-w-0 flex-1">
      <PostHeader {post} />
      <PostBody {post} on:hashtag={handleHashtagSelect} />
      <PostMedia {post} />

      {#if post.poll}
        <div class="mt-3 space-y-2">
          {#each post.poll.options as option}
            <button type="button" on:click={() => votePoll(post.id, option.id)} class="flex w-full items-center justify-between rounded-2xl border border-slate-200 px-4 py-2 text-sm dark:border-white/10">
              <span>{option.text}</span>
              <span class="text-slate-500 dark:text-white/50">{option.percentage}%</span>
            </button>
          {/each}
        </div>
      {/if}

      <ReactionBar
        {post}
        onLike={() => likePost(post.id)}
        onReact={handleReaction}
        onRepost={() => repostPost(post.id)}
        onBookmark={() => bookmarkPost(post.id)}
      />
      <CommentComposer onSubmitComment={(content) => addComment(post.id, content)} />
      <CommentList {post} onToggleLike={(commentId) => toggleCommentLike(post.id, commentId)} />
    </div>
  </div>
</article>
