<script lang="ts">
  import { onMount } from 'svelte';
  import {
    clearHashtagFilter,
    createPost,
    feedFilter,
    feedLoading,
    loadFeed,
    selectedHashtag,
    type FeedFilter,
    type Post
  } from '../../../src/lib/social-store';
  import ActivityRail from '../activity/ActivityRail.svelte';
  import FeedComposer from '../composer/FeedComposer.svelte';
  // @ts-ignore - Svelte component default export is generated by the Svelte compiler.
  import FeedFilters from './FeedFilters.svelte';
  import FeedList from './FeedList.svelte';
  import FeedShell from '../layout/FeedShell.svelte';
  import SocialWidgetPreview from '../widgets/SocialWidgetPreview.svelte';

  let body = '';
  let visibility: Post['visibility'] = 'public';
  let mediaUrl = '';
  let mediaAlt = '';
  let tagsInput = '';

  onMount(() => {
    loadFeed();
  });

  function submitPost() {
    if (!body.trim()) return;
    createPost(body, {
      visibility,
      mediaUrl: mediaUrl.trim() || undefined,
      mediaAlt: mediaAlt.trim() || undefined,
      tags: tagsInput
        .split(',')
        .map((value) => value.trim())
        .filter((value) => value.length > 0)
    });
    body = '';
    visibility = 'public';
    mediaUrl = '';
    mediaAlt = '';
    tagsInput = '';
  }

  function changeFilter(next: FeedFilter) {
    void loadFeed(next);
  }
</script>

<FeedShell
  title="Social"
  subtitle="GitHub-first package source for the flagship Social module. The route file assembles smaller components instead of owning the whole surface."
>
  <svelte:fragment slot="actions">
    <a href="/social/explore" class="rounded-full border border-slate-200 px-4 py-2 text-sm font-medium dark:border-white/10">Explore</a>
    <a href="/social/notifications" class="rounded-full bg-slate-900 px-4 py-2 text-sm font-medium text-white dark:bg-white dark:text-slate-950">Notifications</a>
  </svelte:fragment>

  <FeedFilters value={$feedFilter} onChange={changeFilter} />

  {#if $selectedHashtag}
    <div class="rounded-2xl border border-blue-100 bg-blue-50 px-4 py-3 text-sm text-blue-700 dark:border-blue-500/20 dark:bg-blue-500/10 dark:text-blue-300">
      Filtering by <span class="font-semibold">#{$selectedHashtag}</span>
      <button
        type="button"
        on:click={() => {
          clearHashtagFilter();
          void loadFeed();
        }}
        class="ml-2 rounded-full border border-blue-200 px-2.5 py-1 text-xs font-medium hover:bg-blue-100 dark:border-blue-400/30 dark:hover:bg-blue-500/20"
      >
        Clear
      </button>
    </div>
  {/if}

  <FeedComposer bind:body bind:visibility bind:mediaUrl bind:mediaAlt bind:tagsInput onSubmit={submitPost} />
  <FeedList loading={$feedLoading} />

  <svelte:fragment slot="rail">
    <ActivityRail />
    <SocialWidgetPreview />
  </svelte:fragment>
</FeedShell>
